### ISSUE TITLE
Build & deploy releases to PyPI via Travis CI

### ISSUE THREAD

**Issue by osma** [NatLibFi/Annif-client#3]
We should use Travis CI to build and deploy releases to PyPI, just like Annif itself does nowadays.

**Comment by osma** [comment]
Also [Skosmos-client](https://github.com/NatLibFi/Skosmos-client), which is very similar to annif-client, uses Travis CI for PyPI builds.

**Comment by juhoinkinen** [comment]
Now, after merging #6, releases are handled by GitHub Actions.
